excerpt_separator: ""
highlighter: rouge
markdown: kramdown
url: http://solrevdev.github.io
title: solrevdev
tagline: developer / devops / comedy nerd / amateur boxer
description: A blog about things I find on the web, tools and technologies that I like.
paginate: 5
exclude: ['Rakefile', 'vendor']