excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://solrevdev.github.io
title: solrevdev
tagline: developer / devops / comedy nerd / amateur boxer
description: A blog about things I find on the web, tools and technologies that I like.
paginate: 5